In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

In [2]:
df = pd.read_csv("./data/IMDB Dataset.csv")

In [3]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [4]:
df.sample(5)

                                                  review sentiment
40211  It's not surprising that the majority of highe...  positive
41971  This series has its ups and occasional downs, ...  negative
41678  *May Contain Spoilers* A few weeks after I had...  negative
31513  Didn't Mystic Pizza win the Oscar for that yea...  positive
44412  Franco Zeffirelli's ("The Taming Of The Shrew,...  negative

In [5]:
df_pos = df[df['sentiment']=='positive'][:5000]
df_neg = df[df['sentiment']=='negative'][:5000]

df_reviews = pd.concat([df_pos, df_neg ])

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
train,test = train_test_split(df_reviews,test_size =0.33,random_state=42)

In [8]:
train_x, train_y = train['review'], train['sentiment']
test_x, test_y = test['review'], test['sentiment']

In [9]:
train_y.value_counts()

sentiment
negative    3378
positive    3322
Name: count, dtype: int64

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
tfidf = TfidfVectorizer(stop_words='english')
train_x_vector = tfidf.fit_transform(train_x)
test_x_vector = tfidf.transform(test_x)

In [12]:
train_x.shape

(6700,)

In [13]:
train_x_vector.shape

(6700, 44107)

In [14]:
type(train_x_vector)

scipy.sparse._csr.csr_matrix

In [15]:
primera_resenia = pd.DataFrame.sparse.from_spmatrix(train_x_vector,
                                  index=train_x.index,
                                  columns=tfidf.get_feature_names_out()).iloc[0]

In [16]:
primera_resenia

00           NaN
000          NaN
007          NaN
00am         NaN
00s          NaN
            ...
ísnt         NaN
île          NaN
önsjön       NaN
über         NaN
überwoman    NaN
Name: 6746, Length: 44107, dtype: Sparse[float64, nan]

In [17]:
train_x.iloc[0]

"I happened to rent this movie with my sister in hopes of watching a great entertaining movie, that was humorous, however my expectations were let down. This movie was beyond disgusting and revolting for a PG-13 movie, this should have been rated R for the many mature references that went on in this movie. I wouldn't recommend allowing a 13 year old teen see this.<br /><br />Even if no one under the age of 17 is watching this movie, beware of a truly stupid movie, there's no humor in the movie, just a bunch of disgusting sexual references including a small touch of pedophilia, something that shouldn't even be joked about. <br /><br />I would like to know what happened to PG-13 movies, that were actually safe for actual a 13 year old? This is beyond a deplorable movie and should be re-rated."

In [18]:
primera_resenia[primera_resenia != 0]

00           NaN
000          NaN
007          NaN
00am         NaN
00s          NaN
            ...
ísnt         NaN
île          NaN
önsjön       NaN
über         NaN
überwoman    NaN
Name: 6746, Length: 44107, dtype: Sparse[float64, nan]

In [19]:
train_x.iloc[0]

"I happened to rent this movie with my sister in hopes of watching a great entertaining movie, that was humorous, however my expectations were let down. This movie was beyond disgusting and revolting for a PG-13 movie, this should have been rated R for the many mature references that went on in this movie. I wouldn't recommend allowing a 13 year old teen see this.<br /><br />Even if no one under the age of 17 is watching this movie, beware of a truly stupid movie, there's no humor in the movie, just a bunch of disgusting sexual references including a small touch of pedophilia, something that shouldn't even be joked about. <br /><br />I would like to know what happened to PG-13 movies, that were actually safe for actual a 13 year old? This is beyond a deplorable movie and should be re-rated."

In [20]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(train_x_vector, train_y)

SVC(kernel='linear')

In [21]:
print(svc.predict(tfidf.transform(['A good movie'])))
print(svc.predict(tfidf.transform(['An excellent movie'])))
print(svc.predict(tfidf.transform(['I did not like this movie at all I gave this movie away'])))

['positive']
['positive']
['negative']

In [22]:
print(svc.score(test_x_vector, test_y))

0.8706060606060606

In [23]:
from sklearn.metrics import f1_score

f1_score(test_y,svc.predict(test_x_vector),
          labels = ['positive','negative'],average=None)

array([0.87400413, 0.86701962])

In [24]:
from sklearn.metrics import classification_report

print(classification_report(test_y,
                            svc.predict(test_x_vector),
                            labels = ['positive','negative']))

              precision    recall  f1-score   support

    positive       0.87      0.88      0.87      1678
    negative       0.88      0.86      0.87      1622

    accuracy                           0.87      3300
   macro avg       0.87      0.87      0.87      3300
weighted avg       0.87      0.87      0.87      3300

In [25]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(test_y,
                           svc.predict(test_x_vector),
                           labels = ['positive', 'negative'])
conf_mat

array([[1481,  197],
       [ 230, 1392]])

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

In [27]:
lr = LogisticRegression()
lr.fit(train_x_vector, train_y)

LogisticRegression()

In [28]:
print("LogisticRegression Score:", lr.score(test_x_vector, test_y))
print("LogisticRegression F1:", f1_score(test_y, lr.predict(test_x_vector), labels=['positive','negative'], average=None))
print(classification_report(test_y, lr.predict(test_x_vector), labels=['positive','negative']))
print("Confusion Matrix LR:")
print(confusion_matrix(test_y, lr.predict(test_x_vector), labels=['positive', 'negative']))

LogisticRegression Score: 0.8718181818181818
LogisticRegression F1: [0.87488909 0.86859273]
              precision    recall  f1-score   support

    positive       0.87      0.88      0.87      1678
    negative       0.88      0.86      0.87      1622

    accuracy                           0.87      3300
   macro avg       0.87      0.87      0.87      3300
weighted avg       0.87      0.87      0.87      3300

Confusion Matrix LR:
[[1479  199]
 [ 224 1398]]

In [29]:
gnb = GaussianNB()
gnb.fit(train_x_vector.toarray(), train_y)

GaussianNB()

In [30]:
print("GaussianNB Score:", gnb.score(test_x_vector.toarray(), test_y))
print("GaussianNB F1:", f1_score(test_y, gnb.predict(test_x_vector.toarray()), labels=['positive','negative'], average=None))
print(classification_report(test_y, gnb.predict(test_x_vector.toarray()), labels=['positive','negative']))
print("Confusion Matrix GNB:")
print(confusion_matrix(test_y, gnb.predict(test_x_vector.toarray()), labels=['positive', 'negative']))

GaussianNB Score: 0.6427272727272727
GaussianNB F1: [0.6366718 0.6485842]
              precision    recall  f1-score   support

    positive       0.66      0.62      0.64      1678
    negative       0.63      0.67      0.65      1622

    accuracy                           0.64      3300
   macro avg       0.64      0.64      0.64      3300
weighted avg       0.64      0.64      0.64      3300

Confusion Matrix GNB:
[[1033  645]
 [ 534 1088]]

In [31]:
dt = DecisionTreeClassifier()
dt.fit(train_x_vector, train_y)

DecisionTreeClassifier()

In [32]:
print("DecisionTree Score:", dt.score(test_x_vector, test_y))
print("DecisionTree F1:", f1_score(test_y, dt.predict(test_x_vector), labels=['positive','negative'], average=None))
print(classification_report(test_y, dt.predict(test_x_vector), labels=['positive','negative']))
print("Confusion Matrix DT:")
print(confusion_matrix(test_y, dt.predict(test_x_vector), labels=['positive', 'negative']))

DecisionTree Score: 0.7106060606060606
DecisionTree F1: [0.71191554 0.70928463]
              precision    recall  f1-score   support

    positive       0.72      0.70      0.71      1678
    negative       0.70      0.72      0.71      1622

    accuracy                           0.71      3300
   macro avg       0.71      0.71      0.71      3300
weighted avg       0.71      0.71      0.71      3300

Confusion Matrix DT:
[[1180  498]
 [ 457 1165]]

In [33]:
# Comparación de modelos
models = ['SVM', 'LogisticRegression', 'GaussianNB', 'DecisionTree']
scores = [svc.score(test_x_vector, test_y), lr.score(test_x_vector, test_y), gnb.score(test_x_vector.toarray(), test_y), dt.score(test_x_vector, test_y)]
for model, score in zip(models, scores):
    print(f"{model}: {score:.4f}")

SVM: 0.8706
LogisticRegression: 0.8718
GaussianNB: 0.6427
DecisionTree: 0.7106